import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import React from 'react'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import Script from 'next/script'

const montserrat = Montserrat({
  subsets: ['latin'], 
  variable: '--font-mont' 
})

export const metadata: Metadata = {
  title: 'Esra Sevinc | Software Engineer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/icon?<generated>" type="image/png" sizes="32x32" />
      </head>
      <body className={`${montserrat.className} font-mont bg-light dark:bg-dark w-full min-h-screen`} >
        <Script id='theme-switcher' strategy='beforeInteractive'>
          {`
          if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
            document.documentElement.classList.add('dark')
          } else {
            document.documentElement.classList.remove('dark')
          }
          `}
        </Script>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
